const dayjs = require("dayjs");
const utc = require("dayjs/plugin/utc");
dayjs.extend(utc);
const jwt = require("jsonwebtoken");
const bcrypt= require('bcrypt');


const { insertData,selectData ,selectOneData, selectLastData} = require("../models/MasterModel");
const JWT_SECRET = process.env.JWT_SECRET || "your_jwt_secret_key"

class userController {
  

  async login(req, res) {
    try {
      const { username, password } = req.body;
      

      // === Validation ===
      if (!username || !password) {
        return res.status(400).json({
          success: false,
          error: "Email or Mobile number and password are required",
        });
      }

      // === Fetch user from DB ===
          let condition = `email = '${username}' or mobile_no = '${username}'`


      const users = await selectLastData("users", "id, email, mobile_no, password, role", condition);

      console.log(users);

      const user = users 

      if (!user) {
        return res
          .status(401) 
          .json({ success: false, error: "User not found" });
      }

      //=== Compare password ===
      const isMatch = await bcrypt.compare(password, user.password);
      if (!isMatch) {
        return res
          .status(401)
          .json({ success: false, error: "Invalid credentials" });
      }

      // === Generate JWT ===
      const token = jwt.sign(
        {
          id: user.id,
          email: user.email,
          mobile_no: user.mobile_no,
          role: user.role,
        },
        JWT_SECRET,
       
      );

      // === Send Response ===
      return res.status(200).json({
        success: true,
        message: "Login successful",
        token,
        user: {
          id: user.id,
          name: user.name,
          email: user.email,
          mobile_no: user.mobile_no,
          role: user.role,
        },
      });

    } catch (error) {
      console.error("Login error:", error.message || error);
      return res.status(500).json({
        success: false,
        message: "Sorry, unable to login user",
      });
    }
  }


  

 
 create = async (req, res) => {
  try {
    const { name, email, password, mobile_no, role } = req.body;

    // ✅ Validation
    if (!name || !email || !password || !mobile_no || !role) {
      return res.status(400).json({ error: "All fields are required" });
    }

    if (typeof name !== "string" || name.trim().length < 2) {
      return res
        .status(400)
        .json({ error: "Name must be at least 2 characters" });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ error: "Invalid email format" });
    }

    const passwordRegex = /^(?=.*[0-9]).{6,}$/;
    if (!passwordRegex.test(password)) {
      return res.status(400).json({
        error:
          "Password must be at least 6 characters long and include a number",
      });
    }

    const mobileRegex = /^[0-9]{10}$/; // 10-digit mobile number
    if (!mobileRegex.test(mobile_no)) {
      return res
        .status(400)
        .json({ error: "Mobile number must be 10 digits" });
    }

    // ✅ Created_at should always be generated by server, not client
    const created_at = dayjs().utc().format("YYYY-MM-DD HH:mm:ss");

    // Define default values
    const otp = Math.floor(100000 + Math.random() * 900000); // 6-digit OTP
    const otp_status = false;
    const user_status = true;
    const create_by = ""; // If you need to track admin who created user


const passwordHash=await bcrypt.hash(password,10)

    // ✅ Build columns & values safely
    const columns =
      "name, email, mobile_no, password, otp, otp_status, user_status, role, create_by, created_at";
    const values = [
      name,
      email,
      mobile_no,
      passwordHash,
      otp,
      otp_status,
      user_status,
      role,
      create_by,
      created_at,
    ];

    // Assuming insertData(table, columns, valuesArray)
    const user_id = await insertData("users", columns, values);


    res.status(200).json({
      success: true,
      message: "User created successfully",
      data: { id: user_id, name, email, mobile_no, role, created_at },
    });
  } catch (error) {
    console.error(error);
    res.status(400).json({
      success: false,
      message: "Sorry, unable to create user",
    });
  }
};
}

module.exports = new userController();
